
#
# Only here to clean up the directory
#

clean:
	-rm -rf IVWORK
	-rm -rf INCA_libs
	-rm -rf csrc
	-rm *.pyc
	-rm *.*~ *.~*~ *~
	-rm SERVEROUT
	-rm mem.dump
	-rm verilog.log verilog.key ncverilog.log ncverilog.key verilog.dump
	-rm PYDOC.TXT
	-rm XX YY ZZ
	-rm *.vcd
	-rm apvm.gdbm.db


